[package]
name = "mewz"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.72"
crossterm = "0.26.1"
rodio = "0.17.1"
tokio = "1.29.1"
tui = "0.19.0"
